name: Test and Deploy
on: [push]

jobs:
  run-checks:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Make
        run: sudo apt install make -y
      - name: Set up application dependencies
        run: make requirements
      - name: Set up dev dependencies
        run: make dev-setup
      - name: Run checks
        run: make run-checks
  deploy:
    name: Deploy AWS Infrastructure
    runs-on: ubuntu-latest
    needs: run-checks
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Package Layer Contents
        run: make package-utils
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Initialise Terraform
        run: terraform init
        working-directory: ./tf
      - name: Create Terraform execution plan
        run: terraform plan
        working-directory: ./tf
      - name: Apply and approve execution plan
        run: terraform apply -auto-approve
        working-directory: ./tf
